--------------------------------------------------------------
-- FileName:  bag_list.lua
-- author: 此文件為自動生成，沒有作者。有問題請 @郭浩
--------------------------------------------------------------
ui_bag_list = {};
local p =  ui_bag_list;
p.ID_CTRL_PICTURE_90					     = 95;
p.ID_CTRL_PICTURE_89					     = 94;
p.ID_CTRL_PICTURE_88					     = 93;
p.ID_CTRL_PICTURE_87					     = 92;
p.ID_CTRL_PICTURE_86					     = 91;
p.ID_CTRL_PICTURE_85					     = 90;
p.ID_CTRL_PICTURE_84					     = 89;
p.ID_CTRL_PICTURE_83					     = 88;
p.ID_CTRL_PICTURE_82					     = 87;
p.ID_CTRL_PICTURE_81					     = 86;
p.ID_CTRL_PICTURE_80					     = 85;
p.ID_CTRL_PICTURE_79					     = 84;
p.ID_CTRL_PICTURE_78					     = 83;
p.ID_CTRL_PICTURE_77					     = 82;
p.ID_CTRL_PICTURE_76					     = 81;
p.ID_CTRL_PICTURE_75					     = 80;
p.ID_CTRL_PICTURE_74					     = 79;
p.ID_CTRL_PICTURE_73					     = 78;
p.ID_CTRL_PICTURE_72					     = 77;
p.ID_CTRL_PICTURE_65					     = 76;
p.ID_CTRL_PICTURE_64					     = 75;
p.ID_CTRL_PICTURE_63					     = 74;
p.ID_CTRL_PICTURE_62					     = 73;
p.ID_CTRL_PICTURE_61					     = 72;
p.ID_CTRL_PICTURE_55					     = 66;
p.ID_CTRL_PICTURE_54					     = 65;
p.ID_CTRL_PICTURE_53					     = 64;
p.ID_CTRL_PICTURE_52					     = 60;
p.ID_CTRL_PICTURE_51					     = 58;
p.ID_CTRL_PICTURE_45					     = 52;
p.ID_CTRL_PICTURE_44					     = 51;
p.ID_CTRL_PICTURE_43					     = 50;
p.ID_CTRL_PICTURE_42					     = 49;
p.ID_CTRL_PICTURE_41					     = 48;
p.ID_CTRL_PICTURE_40					     = 47;
p.ID_CTRL_PICTURE_34					     = 42;
p.ID_CTRL_PICTURE_33					     = 41;
p.ID_CTRL_PICTURE_32					     = 40;
p.ID_CTRL_PICTURE_31					     = 39;
p.ID_CTRL_PICTURE_30					     = 38;
p.ID_CTRL_TEXT_EQUIP_LEV4				 = 37;
p.ID_CTRL_TEXT_EQUIP_LEV3				 = 36;
p.ID_CTRL_TEXT_EQUIP_LEV2				 = 35;
p.ID_CTRL_TEXT_EQUIP_LEV1				 = 34;
p.ID_CTRL_PICTURE_STAR4				   = 33;
p.ID_CTRL_PICTURE_STAR3				   = 32;
p.ID_CTRL_PICTURE_STAR2				   = 31;
p.ID_CTRL_PICTURE_STAR1				   = 30;
p.ID_CTRL_PICTURE_EQUIP1				  = 26;
p.ID_CTRL_PICTURE_EQUIP2				  = 27;	--装备标志2
p.ID_CTRL_PICTURE_EQUIP3				  = 28;	--装备标志3
p.ID_CTRL_PICTURE_EQUIP4				  = 29;	--装备标志4
p.ID_CTRL_TEXT_ITEMNAME1				  = 5;	--道具名称
p.ID_CTRL_TEXT_ITEMNAME2				  = 3;	--道具名称
p.ID_CTRL_TEXT_ITEMNAME3				  = 14;	--道具名称
p.ID_CTRL_TEXT_ITEMNAME4				  = 13;	--道具名称
p.ID_CTRL_PICTURE_22					     = 22;
p.ID_CTRL_PICTURE_23					     = 23;
p.ID_CTRL_PICTURE_24					     = 24;
p.ID_CTRL_PICTURE_25					     = 25;
p.ID_CTRL_TEXT_ITEMNUM1				   = 16;
p.ID_CTRL_TEXT_ITEMNUM2				   = 17;
p.ID_CTRL_TEXT_ITEMNUM3				   = 18;
p.ID_CTRL_TEXT_ITEMNUM4				   = 19;
p.ID_CTRL_PICTURE_91					     = 96;
p.ID_CTRL_PICTURE_92					     = 97;
p.ID_CTRL_PICTURE_93					     = 98;
p.ID_CTRL_PICTURE_94					     = 99;
p.ID_CTRL_BUTTON_ITEM1				    = 59;	--物品1
p.ID_CTRL_BUTTON_ITEM2				    = 61;	--物品2
p.ID_CTRL_BUTTON_ITEM3				    = 62;	--物品3
p.ID_CTRL_BUTTON_ITEM4				    = 63;	--物品4
p.ID_CTRL_PICTURE_13					     = 15;
