--------------------------------------------------------------
-- FileName:  card_group_node.lua
-- author: 此文件為自動生成，沒有作者。有問題請 @郭浩
--------------------------------------------------------------
ui_card_group_node = {};
local p =  ui_card_group_node;
p.ID_CTRL_PICTURE_63					     = 63;
p.ID_CTRL_PICTURE_61					     = 61;
p.ID_CTRL_TEXT_53						       = 53;
p.ID_CTRL_TEXT_52						       = 52;
p.ID_CTRL_PICTURE_75					     = 76;	--召唤兽2攻击
p.ID_CTRL_PICTURE_74					     = 75;	--召唤兽2辅助
p.ID_CTRL_PICTURE_73					     = 74;	--召唤兽1攻击标志
p.ID_CTRL_PICTURE_72					     = 73;	--召唤兽1辅助标志
p.ID_CTRL_PICTURE_65					     = 66;
p.ID_CTRL_PICTURE_64					     = 65;
p.ID_CTRL_PICTURE_62					     = 62;
p.ID_CTRL_PICTURE_60					     = 60;
p.ID_CTRL_PICTURE_59					     = 59;
p.ID_CTRL_PICTURE_58					     = 58;
p.ID_CTRL_PICTURE_57					     = 57;
p.ID_CTRL_PICTURE_TEAM3				   = 39;
p.ID_CTRL_PICTURE_TEAM2				   = 38;
p.ID_CTRL_TEXT_TOTAL_DEF				  = 36;
p.ID_CTRL_TEXT_TOTAL_ATK				  = 32;
p.ID_CTRL_BUTTON_PET_2				    = 35;
p.ID_CTRL_PICTURE_TEAM1				   = 37;
p.ID_CTRL_BUTTON_PET_1				    = 34;
p.ID_CTRL_TEXT_PET_NAME_2				 = 33;
p.ID_CTRL_9SLICES_56					     = 56;
p.ID_CTRL_TEXT_PET_NAME_1				 = 31;
p.ID_CTRL_BUTTON_FORMATION			 = 29;
p.ID_CTRL_TEXT_27						       = 27;
p.ID_CTRL_BUTTON_SETFIGHT				 = 22;
p.ID_CTRL_TEXT_CARD_NUM				   = 21;
p.ID_CTRL_TEXT_20						       = 20;
p.ID_CTRL_TEXT_LEV_3					     = 16;
p.ID_CTRL_TEXT_LEV_2					     = 15;
p.ID_CTRL_TEXT_LEV_1					     = 14;
p.ID_CTRL_TEXT_LEV_6					     = 13;
p.ID_CTRL_TEXT_LEV_5					     = 12;
p.ID_CTRL_TEXT_LEV_4					     = 11;
p.ID_CTRL_PICTURE_6					      = 72;
p.ID_CTRL_PICTURE_5					      = 71;
p.ID_CTRL_PICTURE_4					      = 70;
p.ID_CTRL_PICTURE_3					      = 69;
p.ID_CTRL_PICTURE_2					      = 68;
p.ID_CTRL_PICTURE_1					      = 67;
p.ID_CTRL_BUTTON_CARD_3				   = 10;
p.ID_CTRL_BUTTON_CARD_2				   = 9;
p.ID_CTRL_BUTTON_CARD_1				   = 8;
p.ID_CTRL_BUTTON_CARD_6				   = 6;
p.ID_CTRL_BUTTON_CARD_5				   = 5;
p.ID_CTRL_BUTTON_CARD_4				   = 4;
p.ID_CTRL_9SLICES_3					      = 3;
p.ID_CTRL_PICTURE_BG					     = 64;
