--------------------------------------------------------------
-- FileName:  equip_sell_select_list.lua
-- author: 此文件為自動生成，沒有作者。有問題請 @郭浩
--------------------------------------------------------------
ui_equip_sell_select_list = {};
local p =  ui_equip_sell_select_list;
p.ID_CTRL_PICTURE_107					    = 107;
p.ID_CTRL_PICTURE_106					    = 106;
p.ID_CTRL_PICTURE_105					    = 105;
p.ID_CTRL_PICTURE_104					    = 104;
p.ID_CTRL_PICTURE_103					    = 103;
p.ID_CTRL_PICTURE_SEL_5				   = 52;
p.ID_CTRL_PICTURE_SEL_4				   = 51;
p.ID_CTRL_PICTURE_SEL_3				   = 50;
p.ID_CTRL_PICTURE_SEL_2				   = 49;
p.ID_CTRL_PICTURE_SEL_1				   = 47;
p.ID_CTRL_TEXT_LV_5					      = 124;
p.ID_CTRL_TEXT_LV_2					      = 197;
p.ID_CTRL_TEXT_LV_3					      = 196;
p.ID_CTRL_TEXT_LV_4					      = 195;
p.ID_CTRL_TEXT_LV_1					      = 194;
p.ID_CTRL_PICTURE_LV5					    = 46;
p.ID_CTRL_PICTURE_LV4					    = 45;
p.ID_CTRL_PICTURE_LV2					    = 44;
p.ID_CTRL_PICTURE_LV3					    = 43;
p.ID_CTRL_PICTURE_LV1					    = 42;
p.ID_CTRL_TEXT_NAME5					     = 123;
p.ID_CTRL_TEXT_NAME4					     = 122;
p.ID_CTRL_TEXT_NAME3					     = 121;
p.ID_CTRL_TEXT_NAME2					     = 120;
p.ID_CTRL_TEXT_NAME1					     = 119;
p.ID_CTRL_PICTURE_125					    = 129;
p.ID_CTRL_PICTURE_124					    = 128;
p.ID_CTRL_PICTURE_123					    = 127;
p.ID_CTRL_PICTURE_122					    = 126;
p.ID_CTRL_PICTURE_121					    = 125;
p.ID_CTRL_TEXT_DRESSED_5				  = 114;
p.ID_CTRL_TEXT_DRESSED_2				  = 193;
p.ID_CTRL_TEXT_DRESSED_3				  = 192;
p.ID_CTRL_TEXT_DRESSED_4				  = 191;
p.ID_CTRL_TEXT_DRESSED_1				  = 190;
p.ID_CTRL_PICTURE_BD_5				    = 111;
p.ID_CTRL_PICTURE_BD_4				    = 34;
p.ID_CTRL_PICTURE_BD_3				    = 33;
p.ID_CTRL_PICTURE_BD_2				    = 32;
p.ID_CTRL_PICTURE_BD_1				    = 31;
p.ID_CTRL_PICTURE_IMAGE_5				 = 113;
p.ID_CTRL_PICTURE_IMAGE_4				 = 177;
p.ID_CTRL_PICTURE_IMAGE_3				 = 176;
p.ID_CTRL_PICTURE_IMAGE_2				 = 175;
p.ID_CTRL_PICTURE_IMAGE_1				 = 169;
p.ID_CTRL_BUTTON_ITEM_5				   = 110;	--物品1
p.ID_CTRL_BUTTON_ITEM_4				   = 173;	--物品1
p.ID_CTRL_BUTTON_ITEM_3				   = 172;	--物品1
p.ID_CTRL_BUTTON_ITEM_2				   = 171;	--物品1
p.ID_CTRL_BUTTON_ITEM_1				   = 59;	--物品1
p.ID_CTRL_PICTURE_13					     = 15;
p.ID_CTRL_TEXT_112					       = 112;
