--------------------------------------------------------------
-- FileName:  main_interface.lua
-- author: 此文件為自動生成，沒有作者。有問題請 @郭浩
--------------------------------------------------------------
ui_main_interface = {};
local p =  ui_main_interface;
p.ID_CTRL_BUTTON_129					     = 129;
p.ID_CTRL_PICTURE_69					     = 77;
p.ID_CTRL_PICTURE_180					    = 180;
p.ID_CTRL_TEXT_CARD_NAME				  = 54;
p.ID_CTRL_PICTURE_82					     = 90;
p.ID_CTRL_TEXT_81						       = 89;
p.ID_CTRL_TEXT_80						       = 88;
p.ID_CTRL_TEXT_79						       = 87;
p.ID_CTRL_TEXT_78						       = 86;
p.ID_CTRL_TEXT_77						       = 85;
p.ID_CTRL_TEXT_76						       = 84;
p.ID_CTRL_TEXT_75						       = 83;
p.ID_CTRL_TEXT_74						       = 82;
p.ID_CTRL_TEXT_73						       = 81;
p.ID_CTRL_TEXT_72						       = 80;
p.ID_CTRL_TEXT_71						       = 79;
p.ID_CTRL_TEXT_70						       = 78;
p.ID_CTRL_PICTURE_68					     = 76;
p.ID_CTRL_PICTURE_67					     = 75;
p.ID_CTRL_PICTURE_66					     = 74;
p.ID_CTRL_PICTURE_65					     = 73;
p.ID_CTRL_PICTURE_64					     = 72;
p.ID_CTRL_PICTURE_63					     = 71;
p.ID_CTRL_PICTURE_62					     = 70;
p.ID_CTRL_PICTURE_61					     = 69;
p.ID_CTRL_PICTURE_60					     = 68;
p.ID_CTRL_PICTURE_59					     = 67;
p.ID_CTRL_PICTURE_57					     = 65;
p.ID_CTRL_PICTURE_56					     = 64;
p.ID_CTRL_PICTURE_55					     = 63;
p.ID_CTRL_PICTURE_54					     = 62;
p.ID_CTRL_PICTURE_53					     = 61;
p.ID_CTRL_PICTURE_52					     = 52;
p.ID_CTRL_PICTURE_49					     = 49;
p.ID_CTRL_PICTURE_48					     = 48;
p.ID_CTRL_PICTURE_47					     = 47;
p.ID_CTRL_PICTURE_46					     = 46;
p.ID_CTRL_PICTURE_45					     = 45;
p.ID_CTRL_PICTURE_44					     = 44;
p.ID_CTRL_PICTURE_43					     = 43;
p.ID_CTRL_PICTURE_NATURE6				 = 28;
p.ID_CTRL_PICTURE_NATURE5				 = 27;
p.ID_CTRL_PICTURE_NATURE4				 = 26;
p.ID_CTRL_PICTURE_NATURE3				 = 24;
p.ID_CTRL_PICTURE_NATURE2				 = 17;
p.ID_CTRL_PICTURE_NATURE1				 = 16;
p.ID_CTRL_BUTTON_CHA6					    = 23;
p.ID_CTRL_BUTTON_CHA5					    = 22;
p.ID_CTRL_BUTTON_CHA4					    = 21;
p.ID_CTRL_BUTTON_CHA3					    = 20;
p.ID_CTRL_BUTTON_CHA2					    = 19;
p.ID_CTRL_BUTTON_CHA1					    = 18;
p.ID_CTRL_PICTURE_CARD4				   = 58;
p.ID_CTRL_PICTURE_CARD5				   = 59;
p.ID_CTRL_PICTURE_CARD6				   = 60;
p.ID_CTRL_PICTURE_CARD1				   = 55;
p.ID_CTRL_PICTURE_CARD2				   = 56;
p.ID_CTRL_PICTURE_CARD3				   = 57;
p.ID_CTRL_PICTURE_24					     = 31;
p.ID_CTRL_PICTURE_23					     = 30;
p.ID_CTRL_PICTURE_22					     = 29;
p.ID_CTRL_TEXT_MAIL_TIPS_NUM			= 10;	--邮件数量
p.ID_CTRL_PICTURE_MAIL_TIPS_BG		= 8;	--邮件数量通知背景
p.ID_CTRL_BUTTON_MAIL					    = 5;	--邮件按钮
p.ID_CTRL_BUTTON_BG_BTN				   = 11;	--隐藏子界面按钮
p.ID_CTRL_PICTURE_106					    = 106;
p.ID_CTRL_PICTURE_189					    = 189;
p.ID_CTRL_PICTURE_188					    = 188;
p.ID_CTRL_PICTURE_186					    = 186;
p.ID_CTRL_PICTURE_185					    = 185;
p.ID_CTRL_PICTURE_184					    = 184;
p.ID_CTRL_PICTURE_187					    = 187;
p.ID_CTRL_PICTURE_25					     = 25;
p.ID_CTRL_PICTURE_50					     = 50;
p.ID_CTRL_PICTURE_51					     = 51;
p.ID_CTRL_PICTURE_58					     = 66;
