--------------------------------------------------------------
-- FileName: 	load_ani.lua
-- author:		zhangwq, 2013/04/18
-- purpose:		加载特效
--------------------------------------------------------------

--加载特效
LoadAni("common_ui.ani")
LoadAni("bottom_bar.ani")
LoadAni("effect.ani")
LoadAni("sk_test.ani")
LoadAni("token_self.ani")
LoadAni("lancer.ani")
LoadAni("card_icon.ani")
LoadAni("x.ani")
LoadAni("drama.ani")
LoadAni("map.ani")
LoadAni("engine.ani")
LoadAni("ui.ani")
LoadAni("card.ani")
LoadAni("item.ani")
LoadAni("dungeon.ani")
LoadAni("card_battle.ani")
--LoadAni("minicard.ani")
LoadAni("UserImage.ani")
LoadAni("n.ani")
LoadAni("button.ani")
LoadAni("pet_skill.ani")
LoadAni("skill_icon.ani")
LoadAni("skill_effect.ani")
LoadAni("n_battle_buff.ani")
LoadAni("n_bullet.ani")
LoadAni("gacha_pic.ani")
LoadAni("n_battle.ani")
LoadAni("w_battle.ani")
LoadAni("w_battle_buff.ani")
LoadAni("w_bullet.ani")
LoadAni("card_element.ani")
LoadAni("w_drop.ani")
LoadAni("w_battle_res.ani")
LoadAni("card_hero.ani")
LoadAni_Done()

--加载组合特效
LoadAniCombo("combo.anicmb")
LoadAniCombo("lancer_cmb.anicmb")
LoadAniCombo("x_cmb.anicmb")
LoadAniCombo("engine_cmb.anicmb")
LoadAniCombo("ui_cmb.anicmb")
LoadAniCombo("card_battle_cmb.anicmb")
LoadAniCombo("n_cmb.anicmb")
LoadAniCombo_Done()